# Generated by Django 4.2.6 on 2023-10-11 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatrooms',
            old_name='creator',
            new_name='created_user',
        ),
        migrations.RenameField(
            model_name='chatrooms',
            old_name='name',
            new_name='room_name',
        ),
    ]
